territories = {
    'ADR': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ION', 'ALB', 'TRI', 'VEN', 'APO'},
        'units': [],
        'owner': None,
    },
    'AEG': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ION', 'EAS', 'GRE', 'BUL', 'CON', 'SMY'},
        'units': [],
        'owner': None,
    },
    'BAL': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BOT', 'SWE', 'DEN', 'KIE', 'BER', 'PRU', 'LIV'},
        'units': [],
        'owner': None,
    },
    'BAR': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NWG', 'NWY', 'STP'},
        'units': [],
        'owner': None,
    },
    'BLA': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'RUM', 'SEV', 'ARM', 'ANK', 'CON', 'BUL'},
        'units': [],
        'owner': None,
    },
    'BOT': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BAL', 'SWE', 'FIN', 'STP', 'LIV'},
        'units': [],
        'owner': None,
    },
    'EAS': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ION', 'AEG', 'SMY', 'SYR'},
        'units': [],
        'owner': None,
    },
    'ENG': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'MAO', 'IRI', 'WAL', 'LON', 'PIC', 'BRE', 'MID'},
        'units': [],
        'owner': None,
    },
    'GOL': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'WES', 'TYN', 'PIE', 'MAR', 'SPA'},
        'units': [],
        'owner': None,
    },
    'HEL': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NTH', 'HOL', 'KIE'},
        'units': [],
        'owner': None,
    },
    'ION': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ADR', 'AEG', 'EAS', 'ALB', 'GRE', 'APU', 'VEN', 'NAP', 'TUN'},
        'units': [],
        'owner': None,
    },
    'IRI': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ENG', 'MAO', 'NAT', 'LVP', 'WAL'},
        'units': [],
        'owner': None,
    },
    'MAO': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ENG', 'IRI', 'NAT', 'WES', 'SPA', 'POR', 'GAS', 'BRE'},
        'units': [],
        'owner': None,
    },
    'NAT': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'IRI', 'MAO', 'NWG', 'CLY', 'LVP'},
        'units': [],
        'owner': None,
    },
    'NTH': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NWG', 'BAR', 'NWY', 'SKA', 'DEN', 'HEL', 'HOL', 'BEL', 'ENG', 'LON', 'YOR', 'EDI'},
        'units': [],
        'owner': None,
    },
    'NWG': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BAR', 'NTH', 'NAT', 'CLY', 'NWY'},
        'units': [],
        'owner': None,
    },
    'SKA': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NTH', 'NWY', 'SWE', 'DEN'},
        'units': [],
        'owner': None,
    },
    'TYN': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'WES', 'GOL', 'TUS', 'ROM', 'NAP'},
        'units': [],
        'owner': None,
    },
    'WES': {
        'type': 'sea',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'MAO', 'GOL', 'TYN', 'TUS', 'SPA'},
        'units': [],
        'owner': None,
    },
    'ALB': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'GRE', 'SER', 'TRI', 'ADR', 'ION'},
        'units': [],
        'owner': None,
    },
    'ANK': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ARM', 'CON', 'SMY', 'BLA'},
        'units': [],
        'owner': None,
    },
    'APU': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NAP', 'ROM', 'VEN', 'ADR', 'ION'},
        'units': [],
        'owner': None,
    },
    'ARM': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ANK', 'SEV', 'SYR', 'BLA'},
        'units': [],
        'owner': None,
    },
    'BEL': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'HOL', 'PIC', 'RUH', 'ENG', 'NTH'},
        'units': [],
        'owner': None,
    },
    'BER': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'KIE', 'MUN', 'PRU', 'BAL'},
        'units': [],
        'owner': None,
    },
    'BOH': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'GAL', 'MUN', 'SIL', 'TYR', 'VIE'},
        'units': [],
        'owner': None,
    },
    'BRE': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'GAS', 'PIC', 'MID'},
        'units': [],
        'owner': None,
    },
    'BUD': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'GAL', 'RUM', 'SER', 'TRI', 'VIE'},
        'units': [],
        'owner': None,
    },
    'BUL': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'CON', 'GRE', 'RUM', 'SER', 'AEG', 'BLA'},
        'units': [],
        'owner': None,
    },
    'BUR': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'BEL', 'GAS', 'MAR', 'MUN', 'PAR', 'PIC', 'RUH'},
        'units': [],
        'owner': None,
    },
    'CLY': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'APU', 'NAP', 'ROM', 'TUS', 'TYR', 'VEN'},
        'units': [],
        'owner': None,
    },
    'CON': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ANK', 'BUL', 'SMY', 'AEG'},
        'units': [],
        'owner': None,
    },
    'DEN': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'KIE', 'SWE', 'BAL', 'HEL', 'NTH', 'SKA'},
        'units': [],
        'owner': None,
    },
    'EDI': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'CLY', 'LVP', 'YOR', 'NTH'},
        'units': [],
        'owner': None,
    },
    'FIN': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'NOR', 'STP', 'SWE', 'BOT'},
        'units': [],
        'owner': None,
    },
    'GAL': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'BOH', 'BUD', 'RUM', 'SIL', 'UKR', 'VIE', 'WAR'},
        'units': [],
        'owner': None,
    },
    'GAS': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BUR', 'BRE', 'MAR', 'PAR', 'SPA', 'MID'},
        'units': [],
        'owner': None,
    },
    'GRE': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ALB', 'BUL', 'SER', 'AEG', 'ION'},
        'units': [],
        'owner': None,
    },
    'HOL': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'BEL', 'KIE', 'RUH', 'HEL', 'NTH'},
        'units': [],
        'owner': None,
    },
    'KIE': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'BER', 'DEN', 'HOL', 'MUN', 'RUH', 'BAL', 'HEL'},
        'units': [],
        'owner': None,
    },
    'LON': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'WAL', 'YOR', 'NTH', 'ENG'},
        'units': [],
        'owner': None,
    },
    'LVP': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'EDI', 'YOR', 'WAL', 'CLY', 'NAT', 'IRI'},
        'units': [],
        'owner': None,
    },
    'MAR': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'BUR', 'GAS', 'PIE', 'SPA'},
        'units': [],
        'owner': None,
    },
    'MOS': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'LVN', 'SEV', 'STP', 'UKR', 'WAR'},
        'units': [],
        'owner': None,
    },
    'MUN': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'BER', 'BOH', 'BUR', 'KIE', 'RUH', 'SIL', 'TYR'},
        'units': [],
        'owner': None,
    },
    'NAP': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'APU', 'ROM', 'CLA', 'ION', 'TYS'},
        'units': [],
        'owner': None,
    },
    'NWY': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'FIN', 'STP', 'SWE', 'BAR', 'NOR', 'SKA', 'NTH'},
        'units': [],
        'owner': None,
    },
    'PAR': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'BUR', 'GAS', 'PIC'},
        'units': [],
        'owner': None,
    },
    'PIC': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BEL', 'BUR', 'BRE', 'PAR', 'ENG'},
        'units': [],
        'owner': None,
    },
    'PIE': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'MAR', 'TYR', 'TUS', 'LYO'},
        'units': [],
        'owner': None,
    },
    'POR': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'SPA', 'MID', 'NAO'},
        'units': [],
        'owner': None,
    },
    'PRU': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'BER', 'LIV', 'SIL', 'WAR', 'BAL'},
        'units': [],
        'owner': None,
    },
    'ROM': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'APU', 'NAP', 'TUS', 'TYS'},
        'units': [],
        'owner': None,
    },
    'RUM': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'BUL', 'SER', 'SEV', 'UKR', 'BLA'},
        'units': [],
        'owner': None,
    },
    'SER': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'ALB', 'BUD', 'BUL', 'GRE', 'RUM', 'TRI'},
        'units': [],
        'owner': None,
    },
    'SEV': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ARM', 'MOS', 'RUM', 'UKR', 'BLA'},
        'units': [],
        'owner': None,
    },
    'SIL': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'BER', 'BOH', 'GAL', 'MUN', 'PRU', 'WAR'},
        'units': [],
        'owner': None,
    },
    'SMY': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ANK', 'ARM', 'CON', 'SYR', 'AEG'},
        'units': [],
        'owner': None,
    },
    'SPA': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'GAS', 'MAR', 'POR', 'LYO', 'MAO', 'WES'},
        'units': [],
        'owner': None,
    },
    'SWE': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'DEN', 'FIN', 'NWY', 'BAL', 'SKA', 'BOT'},
        'units': [],
        'owner': None,
    },
    'LVO': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'MOS', 'STP', 'WAR'},
        'units': [],
        'owner': None,
    },
    'SYR': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ARM', 'SMY', 'EAS'},
        'units': [],
        'owner': None,
    },
    'TRI': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'ALB', 'BUD', 'SER', 'VIE', 'ADR', 'VEN'},
        'units': [],
        'owner': None,
    },
    'TUN': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'NAF', 'WES', 'TYN', 'ION'},
        'units': [],
        'owner': None,
    },
    'TUS': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'ROM', 'VEN', 'TYS'},
        'units': [],
        'owner': None,
    },
    'TYR': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'BOH', 'MUN', 'VIE', 'STY'},
        'units': [],
        'owner': None,
    },
    'UKR': {
        'type': 'land',
        'supply_center': False,
        'coastal': False,
        'neighbors': {'GAL', 'MOS', 'RUM', 'SEV', 'WAR'},
        'units': [],
        'owner': None,
    },
    'VEN': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'APU', 'ROM', 'TRI', 'TUS', 'ADR'},
        'units': [],
        'owner': None,
    },
    'VIE': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'BOH', 'BUD', 'GAL', 'STY', 'TRI', 'TYR'},
        'units': [],
        'owner': None,
    },
    'WAL': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'CLY', 'LVP', 'LON', 'YOR', 'IRI'},
        'units': [],
        'owner': None,
    },
    'STP': {
        'type': 'land',
        'supply_center': True,
        'coastal': True,
        'neighbors': {'BAR', 'FIN', 'LVN', 'MOS', 'NOR'},
        'units': [],
        'owner': None,
    },
    'WAR': {
        'type': 'land',
        'supply_center': True,
        'coastal': False,
        'neighbors': {'GAL', 'MOS', 'PRU', 'SIL', 'UKR'},
        'units': [],
        'owner': None,
    },
    'YOR': {
        'type': 'land',
        'supply_center': False,
        'coastal': True,
        'neighbors': {'EDI', 'LON', 'LVP', 'NTH', 'NWG', 'WAL'},
        'units': [],
        'owner': None,
    }

}
def get_territories():
    return territories
